apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: myports 
    port: {{ .Values.service.port | quote }}
    protocol: {{ .Values.service.protocol }}
    targetPort: {{ .Values.service.targetport | quote }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
