apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace.name }}
spec:
  ports:
  - name: myports 
    port: {{ .Values.service.port }}
    protocol: {{ .Values.service.protocol }}
    {{ if eq .Values.service.targetport nil }}
    targetport: {{ .Values.service.port }}
    {{ else }}
    targetPort: {{ .Values.service.targetport }}
    {{ end }}
  selector:
    app: techtrends
  type: {{ .Values.service.type }}
status:
  loadBalancer: {}
